spring:
  application:
    name: cache
  datasource:
    url: jdbc:postgresql://localhost:5432/aidb
    username: admin
    password: 123456
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml
